const products = [
  {
    id: 1,
    name: "Purple OUD",
    description: "A deep, luxurious oud blended with warm amber and exotic spices.",
    type: "Perfume",
    inspiredBy: "Purple Oud (Dior)",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Day/Night",
    family: "Amber Woody",
    accords: ["Woody", "Spicy", "Citrus", "Oud"],
    top: "Mandarin Orange",
    mid: "Pink Pepper, Saffron",
    base: "Oud (Agarwood)",
    price: 399,
    image: "purple_oud.png",
    images: [
      "purple_oud.jpg", 
      "purple_oud1.png", 
      "purple_oud2.png", 
      "purple_oud3.png", 
      "purple_oud4.png", 
      "purple_oud5.png", 
      "purple_oud6.png", 
      "purple_oud7.png", 
      "purple_oud100.png"
    ]
  },
  {
    id: 2,
    name: "Pulse Royale",
    description: "Fresh aromatic notes with a smooth woody and masculine finish.",
    type: "Perfume",
    inspiredBy: "CR-7",
    gender: "Unisex",
    season: "All Season",
    time: "Day",
    family: "Aromatic Fougère",
    accords: ["Aromatic", "Woody", "Powdery", "Warm Spicy"],
    top: "Lavender, Cardamom, Artemisia, Bergamot",
    mid: "Tobacco, Cinnamon, Cedar, Iris",
    base: "Vanilla, Musk, Sandalwood, Amber",
    price: 399,
    image: "pulse_royale.png",
    images: [
      "pulse_royale.jpg", 
      "pulse_royale1.png", 
      "pulse_royale2.png", 
      "pulse_royale3.png", 
      "pulse_royale4.png", 
      "pulse_royale5.png", 
      "pulse_royale6.png", 
      "pulse_royale7.png", 
      "pulse_royale100.png"
    ]
  },
  {
    id: 3,
    name: "Aqua Wave",
    description: "A fresh aquatic fragrance with citrus and marine notes. Clean, crisp and refreshing.",
    type: "Perfume",
    inspiredBy: "Acqua Di Gio",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day/Night",
    family: "Aromatic Aquatic",
    accords: ["Citrus", "Aromatic", "Marine", "Fresh Spicy"],
    top: "Lime, Lemon, Bergamot, Jasmine, Orange, Mandarin",
    mid: "Sea Notes, Jasmine, Calone, Peach, Freesia",
    base: "White Musk, Cedar, Oakmoss, Patchouli, Amber",
    price: 399,
    image: "aqua_wave.png",
    images: [
      "aqua_wave.jpg", 
      "aqua_wave1.png", 
      "aqua_wave2.png", 
      "aqua_wave3.png", 
      "aqua_wave4.png", 
      "aqua_wave5.png", 
      "aqua_wave6.png", 
      "aqua_wave7.png", 
      "aqua_wave100.png"
    ]
  },
  {
    id: 4,
    name: "Eternal Elixir",
    description: "An intense spicy aromatic scent with powerful depth. Perfect for bold evenings.",
    type: "Perfume",
    inspiredBy: "Dior Sauvage Elixir",
    gender: "Male",
    season: "All Season",
    time: "Night",
    family: "Aromatic Spicy",
    accords: ["Warm Spicy", "Fresh Spicy", "Woody", "Aromatic"],
    top: "Nutmeg, Cinnamon, Cardamom, Grapefruit",
    mid: "Lavender",
    base: "Licorice, Sandalwood, Amber, Patchouli, Vetiver",
    price: 399,
    image: "eternal_elixir.png",
    images: [
      "eternal_elixir.jpg", 
      "eternal_elixir1.png", 
      "eternal_elixir2.png", 
      "eternal_elixir3.png", 
      "eternal_elixir4.png", 
      "eternal_elixir5.png", 
      "eternal_elixir6.png", 
      "eternal_elixir7.png", 
      "eternal_elixir100.png"
    ]
  },
  {
    id: 5,
    name: "Golden Blush",
    description: "Soft florals with creamy vanilla and almond sweetness. Elegant and feminine.",
    type: "Perfume",
    inspiredBy: "Good Girl Blush",
    gender: "Female",
    season: "All Season",
    time: "Day",
    family: "Chypre Floral",
    accords: ["Floral", "Vanilla", "Citrus", "Powdery", "Almond"],
    top: "Bergamot, Bitter Almond",
    mid: "Peony, Ylang-Ylang",
    base: "Vanilla, Coumarin (Tonka)",
    price: 399,
    image: "golden_blush.png",
    images: [
      "golden_blush.jpg", 
      "golden_blush1.png", 
      "golden_blush2.png", 
      "golden_blush3.png", 
      "golden_blush4.png", 
      "golden_blush5.png", 
      "golden_blush6.png", 
      "golden_blush7.png", 
      "golden_blush100.png"
    ]
  },
  {
    id: 6,
    name: "Intense Suede",
    description: "Warm spicy sweetness with smooth suede and vanilla. Sensual and addictive.",
    type: "Perfume",
    inspiredBy: "Stronger With You Intensely",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Fougère",
    accords: ["Warm Spicy", "Amber", "Vanilla", "Sweet"],
    top: "Pink Pepper, Juniper, Violet",
    mid: "Toffee, Cinnamon, Lavender, Sage",
    base: "Vanilla, Tonka Bean, Amber, Suede",
    price: 399,
    image: "intense_suede.png",
    images: [
      "intense_suede.jpg", 
      "intense_suede1.png", 
      "intense_suede2.png", 
      "intense_suede3.png", 
      "intense_suede4.png", 
      "intense_suede5.png", 
      "intense_suede6.png", 
      "intense_suede7.png", 
      "intense_suede100.png"
    ]
  },
  {
    id: 7,
    name: "Cool Essence",
    description: "Crisp green freshness with citrus and woods. Sporty, clean and refreshing.",
    type: "Perfume",
    inspiredBy: "Polo Sport",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Aromatic Green",
    accords: ["Aromatic", "Fresh Spicy", "Green", "Citrus"],
    top: "Mint, Aldehydes, Lavender, Bergamot, Mandarin, Lemon",
    mid: "Seagrass, Ginger, Jasmine, Geranium, Rosewood",
    base: "Musk, Sandalwood, Cedar, Guaiac Wood, Amber",
    price: 399,
    image: "cool_essence.png",
    images: [
      "cool_essence.jpg", 
      "cool_essence1.png", 
      "cool_essence2.png", 
      "cool_essence3.png", 
      "cool_essence4.png", 
      "cool_essence5.png", 
      "cool_essence6.png", 
      "cool_essence7.png", 
      "cool_essence100.png"
    ]
  },
  {
    id: 8,
    name: "Divine Essence",
    description: "A luxurious vanilla-forward fragrance with aromatic warmth. Comforting yet powerful.",
    type: "Perfume",
    inspiredBy: "Burberry Goddess",
    gender: "Female",
    season: "All Season",
    time: "Day/Night",
    family: "Aromatic Gourmand",
    accords: ["Vanilla", "Aromatic", "Sweet", "Lavender"],
    top: "Vanilla Infusion, Lavender, Cacao, Ginger",
    mid: "Vanilla Caviar",
    base: "Vanilla Absolute",
    price: 399,
    image: "divine_essence.png",
    images: [
      "divine_essence.jpg", 
      "divine_essence1.png", 
      "divine_essence2.png", 
      "divine_essence3.png", 
      "divine_essence4.png", 
      "divine_essence5.png", 
      "divine_essence6.png", 
      "divine_essence7.png", 
      "divine_essence100.png"
    ]
  },
  {
    id: 9,
    name: "Vanilla Blossom",
    description: "Sweet vanilla blended with florals and amber. Cozy, warm and irresistible.",
    type: "Perfume",
    inspiredBy: "Kayali Vanilla 28",
    gender: "Female",
    season: "Autumn-Winter",
    time: "Night",
    family: "Amber Vanilla",
    accords: ["Vanilla", "Sweet", "Amber", "Powdery", "Floral"],
    top: "Vanilla Orchid, Jasmine",
    mid: "Brown Sugar, Tonka Bean",
    base: "Amber, Amberwood, Musk, Patchouli",
    price: 399,
    image: "vanilla_blossom.png",
    images: [
      "vanilla_blossom.jpg", 
      "vanilla_blossom1.png", 
      "vanilla_blossom2.png", 
      "vanilla_blossom3.png", 
      "vanilla_blossom4.png", 
      "vanilla_blossom5.png", 
      "vanilla_blossom6.png", 
      "vanilla_blossom7.png", 
      "vanilla_blossom100.png"
    ]
  },
  {
    id: 10,
    name: "Eternal Sauvage",
    description: "Fresh spicy citrus with aromatic woods. Powerful, masculine and long-lasting.",
    type: "Perfume",
    inspiredBy: "Dior Sauvage (EDT)",
    gender: "Male",
    season: "All Season",
    time: "Day/Night",
    family: "Aromatic Fougère",
    accords: ["Fresh Spicy", "Amber", "Citrus", "Aromatic"],
    top: "Calabrian Bergamot, Pepper",
    mid: "Sichuan Pepper, Lavender, Pink Pepper, Vetiver, Patchouli",
    base: "Ambroxan, Cedar, Labdanum",
    price: 399,
    image: "eternal_sauvage.png",
    images: [
      "eternal_sauvage.jpg", 
      "eternal_sauvage1.png", 
      "eternal_sauvage2.png", 
      "eternal_sauvage3.png", 
      "eternal_sauvage4.png", 
      "eternal_sauvage5.png", 
      "eternal_sauvage6.png", 
      "eternal_sauvage7.png", 
      "eternal_sauvage100.png"
    ]
  },
  {
    id: 11,
    name: "Invictus",
    description: "Fresh aquatic scent with salty marine notes. Energetic, youthful and bold.",
    type: "Perfume",
    inspiredBy: "Invictus Aqua",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Woody Aquatic",
    accords: ["Citrus", "Marine", "Aquatic", "Salty"],
    top: "Yuzu, Grapefruit, Pink Pepper",
    mid: "Sea Water, Violet Leaf",
    base: "Ambergris, Amberwood, Guaiac Wood",
    price: 399,
    image: "invictus.png",
    images: [
      "invictus.jpg", 
      "invictus1.png", 
      "invictus2.png", 
      "invictus3.png", 
      "invictus4.png", 
      "invictus5.png", 
      "invictus6.png", 
      "invictus7.png", 
      "invictus100.png"
    ]
  },
  {
    id: 12,
    name: "Bleu Voyage",
    description: "Citrus freshness balanced with woody incense notes. Sophisticated and timeless.",
    type: "Perfume",
    inspiredBy: "Bleu de Chanel",
    gender: "Male",
    season: "All Season",
    time: "Day/Night",
    family: "Woody Aromatic",
    accords: ["Citrus", "Woody", "Warm Spicy", "Aromatic"],
    top: "Grapefruit, Lemon, Mint, Pink Pepper",
    mid: "Ginger, Nutmeg, Jasmine, Iso E Super",
    base: "Incense, Vetiver, Cedar, Sandalwood, Patchouli",
    price: 499,
    image: "bleu_voyage.png",
    images: [
      "bleu_voyage.jpg", 
      "bleu_voyage1.png", 
      "bleu_voyage2.png", 
      "bleu_voyage3.png", 
      "bleu_voyage4.png", 
      "bleu_voyage5.png", 
      "bleu_voyage6.png", 
      "bleu_voyage7.png", 
      "bleu_voyage100.png"
    ]
  },
  {
    id: 13,
    name: "Aventus",
    description: "Iconic fruity-smoky fragrance with woods and musk. Confident and commanding.",
    type: "Perfume",
    inspiredBy: "Creed Aventus",
    gender: "Male",
    season: "All Season",
    time: "Day/Night",
    family: "Chypre Fruity",
    accords: ["Fruity", "Sweet", "Leather", "Woody", "Smoky"],
    top: "Pineapple, Bergamot, Black Currant, Apple",
    mid: "Birch, Patchouli, Moroccan Jasmine, Rose",
    base: "Musk, Oakmoss, Ambergris, Vanilla",
    price: 449,
    image: "aventus.png",
    images: [
      "aventus.jpg", 
      "aventus1.png", 
      "aventus2.png", 
      "aventus3.png", 
      "aventus4.png", 
      "aventus5.png", 
      "aventus6.png", 
      "aventus7.png", 
      "aventus100.png"
    ]
  },
  {
    id: 14,
    name: "Golden Flora",
    description: "Bright floral bouquet with fruity sweetness. Soft, joyful and elegant.",
    type: "Perfume",
    inspiredBy: "Gucci Flora Gorgeous Gardenia",
    gender: "Female",
    season: "Spring-Summer",
    time: "Day",
    family: "Floral",
    accords: ["White Floral", "Sweet", "Fruity", "Floral"],
    top: "Pear Blossom, Red Berries, Italian Mandarin",
    mid: "Gardenia, Jasmine, Frangipani",
    base: "Brown Sugar, Patchouli",
    price: 399,
    image: "golden_flora.png",
    images: [
      "golden_flora.png", 
      "golden_flora1.png", 
      "golden_flora2.png", 
      "golden_flora3.png", 
      "golden_flora4.png", 
      "golden_flora5.png", 
      "golden_flora6.png", 
      "golden_flora7.png", 
      "golden_flora100.png"
    ]
  },
  {
    id: 15,
    name: "Fresh Impact",
    description: "Sparkling citrus with aromatic spice and woods. Clean, uplifting and modern.",
    type: "Perfume",
    inspiredBy: "Louis Vuitton Imagination",
    gender: "Unisex",
    season: "Spring-Summer",
    time: "Day",
    family: "Citrus Aromatic",
    accords: ["Citrus", "Aromatic", "Fresh Spicy", "Woody"],
    top: "Citron, Calabrian Bergamot, Sicilian Orange",
    mid: "Tunisian Neroli, Nigerian Ginger, Ceylon Cinnamon",
    base: "Chinese Black Tea, Ambroxan, Guaiac Wood, Olibanum",
    price: 449,
    image: "fresh_impact.png",
    images: [
      "fresh_impact.jpg", 
      "fresh_impact1.png", 
      "fresh_impact2.png", 
      "fresh_impact3.png", 
      "fresh_impact4.png", 
      "fresh_impact5.png", 
      "fresh_impact6.png", 
      "fresh_impact7.png", 
      "fresh_impact100.png"
    ]
  },
  {
    id: 15,
    name: "Chocolate Musk",
    image: "sweet chocolate gourmond.png",
    images: ["sweet chocolate gourmond.png", "chocolatem1.jpg", "chocolatem2.jpg", "info.jpga"],
    description: "A rich gourmand attar blending creamy chocolate with soft musk and powdery warmth, creating a comforting and addictive aroma.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Gourmand",
    accords: ["Gourmand", "Musky", "Powdery"],
    top: "Milk Chocolate, Cinnamon, Vanilla",
    mid: "Spicy Notes, Rose",
    base: "White Musk, Sandalwood, Myrrh, Amber",
    price: 49
  },
  {
    id: 17,
    name: "Iceberg",
    image: "fresh_auqatic.png",
    images: ["fresh_auqatic.png", "iceberga1.jpg", "iceberga2.jpg", "infoa.jpg"],
    description: "A concentrated attar version of a fresh citrus floral fragrance, offering enhanced longevity and smooth clarity.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Citrus",
    accords: ["Citrus", "Fresh", "Floral"],
    top: "Galbanum, Bergamot, Basil, Orange Blossom, Lemon, Peach",
    mid: "Lily, Lily-of-the-Valley, Jasmine, Orris Root, Rose, Ylang-Ylang",
    base: "Oakmoss, Cedar, Vetiver, Sandalwood, Musk, Amber",
    price: 49
  },
  {
    id: 18,
    name: "Dubai Gold",
    image: "sweet gourmond.png",
    images: ["sweet gourmond.png", "dubaig1.jpg", "dubaig2.jpg", "infoa.jpg"],
    description: "A luxurious Middle Eastern attar where rich oud meets warm amber and exotic spices, ideal for bold evening wear.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental",
    accords: ["Oud", "Amber", "Spicy"],
    top: "Saffron, Bitter Orange, Brandy",
    mid: "Cedarwood, Guaiac Wood, Juniper",
    base: "Patchouli, Sandalwood, Musk, Amber",
    price: 59
  },
  {
    id: 20,
    name: "Cool Tide",
    image: "fresh marine.png",
    images: ["fresh marine.png", "coolta1.jpg", "coolta2.jpg", "infoa.jpg"],
    description: "A long-lasting attar interpretation of a classic aquatic fragrance with cooling freshness and floral depth.",
    type: "Attar",
    inspiredBy: "Davidoff CoolWater",
    gender: "Unisex",
    season: "Spring-Summer",
    time: "Day",
    family: "Aquatic Fresh",
    accords: ["Fresh", "Floral", "Aquatic"],
    top: "Melon, Lotus, Lemon, Pineapple, Quince, Calone, Lily",
    mid: "Lotus, Water Lily, Lily-of-the-Valley, Jasmine, Honey, Hawthorn, Rose",
    base: "Musk, Vetiver, Raspberry, Blackberry, Violet Root, Peach, Sandalwood",
    price: 69
  },
  {
    id: 21,
    name: "Red Musk",
    image: "alln.png",
    images: ["alln.png", "redma1.jpg", "redma2.jpg", "infoa.jpg"],
    description: "A deep and sensual musky attar accented with warm spices and tobacco nuances for evening wear.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Musky",
    accords: ["Musky", "Spicy"],
    top: "Pepper",
    mid: "Cinnamon",
    base: "Tobacco, Musk",
    price: 69
  },
  {
    id: 23,
    name: "Chrome Breeze",
    image: "breeze.png",
    images: ["breeze.png", "chromeba1.jpg", "chromeba2.jpg", "infoa.jpg"],
    description: "A concentrated attar version of a fresh woody citrus fragrance with enhanced smoothness and longevity.",
    type: "Attar",
    inspiredBy: "Azzaro Chrome",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Woody",
    accords: ["Fresh", "Woody", "Citrus"],
    top: "Lemon, Rosemary, Bergamot, Neroli, Pineapple",
    mid: "Jasmine, Cyclamen, Oakmoss, Coriander",
    base: "Musk, Cedar, Oakmoss, Sandalwood, Cardamom, Tonka Bean, Rosewood",
    price: 59
  },
  {
    id: 24,
    name: "Luminous Veil",
    image: "luminous_veil.png",
    images: [
      "luminous_veil.jpg", 
      "luminous_veil1.png", 
      "luminous_veil2.png", 
      "luminous_veil3.png", 
      "luminous_veil4.png", 
      "luminous_veil5.png", 
      "luminous_veil6.png", 
      "luminous_veil7.png", 
      "luminous_veil100.png"
    ],
    description: "A luminous floral-fruity perfume with soft powdery tones, expressing elegance, femininity, and charm.",
    type: "Perfume",
    inspiredBy: "Dior J'adore",
    gender: "Female",
    season: "Spring-Summer",
    time: "Day",
    family: "Floral",
    accords: ["Floral", "Fruity", "Powdery"],
    top: "Pear, Melon, Magnolia, Peach, Mandarin Orange, Bergamot",
    mid: "Jasmine, Lily-of-the-Valley, Tuberose, Freesia, Rose, Orchid, Plum, Violet",
    base: "Musk, Vanilla, Blackberry, Cedar",
    price: 399
  },
  {
    id: 25,
    name: "Luminous Veil",
    image: "norm1.png",
    images: ["norm1.png", "luminousva1.jpg", "luminousva2.jpg", "infoa.jpg"],
    description: "A refined attar rendition of a floral bouquet enriched with fruity sweetness and powdery elegance.",
    type: "Attar",
    inspiredBy: "Dior J'adore",
    gender: "Female",
    season: "Spring-Summer",
    time: "Day",
    family: "Floral",
    accords: ["Floral", "Fruity", "Powdery"],
    top: "Pear, Melon, Magnolia, Peach, Mandarin Orange, Bergamot",
    mid: "Jasmine, Lily-of-the-Valley, Tuberose, Freesia, Rose, Orchid, Plum, Violet",
    base: "Musk, Vanilla, Blackberry, Cedar",
    price: 89
  },
  {
    id: 26,
    name: "Golden Flora",
    image: "female floral.png",
    images: ["female floral.png", "goldenfa1.jpg", "goldenfa2.jpg", "infoa.jpg"],
    description: "A bright and elegant floral-fruity attar with fresh citrus nuances, radiating youthful femininity and charm.",
    type: "Attar",
    inspiredBy: "Gucci Flora",
    gender: "Female",
    season: "Spring-Summer",
    time: "Day",
    family: "Floral",
    accords: ["Floral", "Fruity", "Citrus"],
    top: "Peony, Citrus Fruits, Mandarin Orange",
    mid: "Osmanthus, Rose",
    base: "Sandalwood, Patchouli, Pink Pepper",
    price: 69
  },
  {
    id: 27,
    name: "Cool Essence",
    image: "coolea.png",
    images: ["coolea.png", "coolea1.jpg", "coolea2.jpg", "infoa.jpg"],
    description: "A sporty and energetic fresh aromatic fragrance inspired by outdoor vitality and aquatic freshness.",
    type: "Attar",
    inspiredBy: "Polo Sports",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Aromatic",
    accords: ["Fresh", "Aromatic", "Citrus"],
    top: "Mint, Aldehydes, Lavender, Bergamot, Mandarin Orange, Lemon, Artemisia, Neroli",
    mid: "Seagrass, Jasmine, Ginger, Geranium, Rose, Cyclamen, Brazilian Rosewood",
    base: "Musk, Sandalwood, Cedar, Guaiac Wood, Amber",
    price: 89
  },
  {
    id: 28,
    name: "Majmua",
    image: "norm2.png",
    images: ["norm2.png", "majmuaa1.jpg", "majmuaa2.jpg", "infoa.jpg"],
    description: "A classic traditional attar blending floral, herbal, and musky tones, deeply rooted in Indo-Arabic perfumery.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day/Night",
    family: "Oriental Floral",
    accords: ["Floral", "Herbal", "Musky"],
    top: "Kewda (Screw Pine), Green Notes",
    mid: "Rose (Ruh Gulab), Hina (Henna)",
    base: "Vetiver (Khus), Sandalwood",
    price: 69
  },
  {
    id: 29,
    name: "Majmua Premium",
    image: "prem5.png",
    images: ["prem5.png", "majmuapap1.jpg", "majmuapap2.jpg", "infoa.jpg"],
    description: "A richer and more refined version of Majmua with enhanced depth, smoothness, and lasting power.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day/Night",
    family: "Oriental Floral",
    accords: ["Floral", "Herbal", "Musky"],
    top: "Kewda (Screw Pine), Green Notes",
    mid: "Rose (Ruh Gulab), Hina (Henna)",
    base: "Vetiver (Khus), Sandalwood",
    price: 899
  },
  {
    id: 30,
    name: "Mukhallat",
    image: "smoky, oudy, spicy.png",
    images: ["smoky, oudy, spicy.png", "mukhallata1.jpg", "mukhallata2.jpg", "infoa.jpg"],
    description: "A bold oriental attar combining oud, amber, and spices for a warm and luxurious evening presence.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental",
    accords: ["Oriental", "Amber", "Spicy"],
    top: "Oud (Agarwood)",
    mid: "Saffron",
    base: "Musk, Amber, Woody Notes",
    price: 69
  },
  {
    id: 31,
    name: "Mukhallat Premium",
    image: "all.png",
    images: ["all.png", "mukhallatpa1.jpg", "mukhallatpa2.jpg", "infoa.jpg"],
    description: "A premium interpretation of Mukhallat offering deeper oud richness and smoother amber warmth.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental",
    accords: ["Oriental", "Amber", "Spicy"],
    top: "Oud (Agarwood)",
    mid: "Saffron",
    base: "Musk, Amber, Woody Notes",
    price: 999
  },
  {
    id: 32,
    name: "Ameer Al OUD",
    image: "smoky, oudy, spicy.png",
    images: ["smoky, oudy, spicy.png", "ameeraa1.jpg", "ameeraa2.jpg", "infoa.jpg"],
    description: "A sweet woody oud fragrance with vanilla warmth, balancing richness and smooth gourmand undertones.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Oriental",
    accords: ["Woody", "Sweet", "Amber"],
    top: "Oud, Woody Notes",
    mid: "Vanilla, Sugar",
    base: "Agarwood (Oud), Sandalwood, Herbal Notes",
    price: 89
  },
  {
    id: 33,
    name: "Ameer Al OUD Premium",
    image: "oudyspicyfresh.png",
    images: ["oudyspicyfresh.png", "ameerapa1.jpg", "ameerapa2.jpg", "infoa.jpg"],
    description: "A premium and smoother oud blend with intensified sweetness and long-lasting woody depth.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Oriental",
    accords: ["Woody", "Sweet", "Amber"],
    top: "Oud, Woody Notes",
    mid: "Vanilla, Sugar",
    base: "Agarwood (Oud), Sandalwood, Herbal Notes",
    price: 249
  },
  {
    id: 34,
    name: "Shay Oud",
    image: "smoky.png",
    images: ["smoky.png", "shayoa1.jpg", "shayoa2.jpg", "infoa.jpg"],
    description: "A warm oriental oud fragrance enriched with honeyed sweetness and smoky incense accents.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Woody",
    accords: ["Woody", "Oriental", "Honey"],
    top: "Frankincense (Luban)",
    mid: "Honey",
    base: "Agarwood (Oud), Musk",
    price: 99
  },
  {
    id: 35,
    name: "Shay Oud Premium",
    image: "oudshay.png",
    images: ["oudshay.png", "shayopa1.jpg", "shayopa2.jpg", "infoa.jpg"],
    description: "A deeper and more refined version of Shay Oud with enhanced honeyed warmth and resinous oud.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Woody",
    accords: ["Woody", "Oriental", "Honey"],
    top: "Frankincense (Luban)",
    mid: "Honey",
    base: "Agarwood (Oud), Musk",
    price: 239
  },
  {
    id: 36,
    name: "Jannatul Ferdous",
    image: "norm7.png",
    images: ["norm7.png", "jannatulfa1.jpg", "jannatulfa2.jpg", "infoa.jpg"],
    description: "A fresh herbal-floral attar with green and spicy undertones, traditionally worn for daytime serenity.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Spring-Summer",
    time: "Day",
    family: "Herbal Floral",
    accords: ["Herbal", "Floral", "Spicy"],
    top: "Lotus, Gardenia, Green Notes",
    mid: "Rose, Grass",
    base: "Herbal Notes, Woody Notes",
    price: 69
  },
  {
    id: 37,
    name: "Zam Zam",
    image: "breeze.png",
    images: ["breeze.png", "zamza1.jpg", "zamza2.jpg", "infoa.jpg"],
    description: "A clean and uplifting fresh aromatic attar with watery florals and gentle musky warmth.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Aromatic",
    accords: ["Fresh", "Aromatic"],
    top: "Bergamot, Mint, Watercress",
    mid: "Lilies, Iris, Jasmine",
    base: "Woody Notes, Musk, Apricot",
    price: 69
  },
  {
    id: 38,
    name: "Magnet",
    image: "smoky.png",
    images: ["smoky.png", "magneta1.jpg", "magneta2.jpg", "infoa.jpg"],
    description: "A complex floral-woody fragrance with fruity sweetness and resinous warmth, bold yet elegant.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day/Night",
    family: "Woody Floral",
    accords: ["Floral", "Woody", "Mossy"],
    top: "Red Berries, Black Currant, Cassia, Litchi, Pineapple, Melon",
    mid: "Green Leaves, Basil, Almond Blossom, Iris, Freesia, Jasmine, Rose",
    base: "Caramel, Vanilla, Patchouli, Benzoin, Musk, Sandalwood, Amber, Vetiver",
    price: 49
  },
  {
    id: 39,
    name: "Aqua Wave",
    image: "aqua fresh.png",
    images: ["aqua fresh.png", "aquawa1.jpg", "aquawa2.jpg", "infoa.jpg"],
    description: "A marine-fresh fragrance inspired by ocean air, blending citrus brightness with salty aquatic notes.",
    type: "Attar",
    inspiredBy: "Aqua De Gio",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Marine Fresh",
    accords: ["Fresh", "Marine", "Citrus"],
    top: "Lime, Lemon, Bergamot, Jasmine, Orange, Mandarin Orange, Neroli",
    mid: "Sea Notes, Jasmine, Calone, Rosemary, Peach, Freesia, Cyclamen",
    base: "White Musk, Cedar, Oakmoss, Patchouli, Amber",
    price: 69
  },
  {
    id: 40,
    name: "Blue Wave",
    image: "fresh_auqatic.png",
    images: ["fresh_auqatic.png", "bluewa1.jpg", "bluewa2.jpg", "infoa.jpg"],
    description: "A light and refreshing citrus-aquatic attar designed for everyday summer freshness.",
    type: "Attar",
    inspiredBy: "",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Citrus",
    accords: ["Fresh", "Citrus", "Fruity"],
    top: "Bergamot, Mandarin Orange",
    mid: "Aquatic Accords, Lavender",
    base: "Amber, Woody Notes, Musk",
    price: 69
  },
  {
    id: 41,
    name: "Blue Water",
    image: "norm6.png",
    images: ["norm6.png", "bluewa1.jpg", "bluewa2.jpg", "infoa.jpg"],
    description: "A clean and refreshing aromatic aquatic attar with marine freshness and woody undertones.",
    type: "Attar",
    inspiredBy: "",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Aromatic",
    accords: ["Fresh", "Aromatic"],
    top: "Sea Water, Citrus, Green Notes",
    mid: "Neroli, Geranium",
    base: "Oakmoss, Cedar",
    price: 69
  },
  {
    id: 42,
    name: "Velour Si",
    image: "female floral.png",
    images: ["female floral.png", "veloursa1.jpg", "veloursa2.jpg", "infoa.jpg"],
    description: "A sophisticated fruity-floral fragrance with warm vanilla undertones, elegant and feminine.",
    type: "Attar",
    inspiredBy: "Armani Si",
    gender: "Female",
    season: "Autumn-Winter",
    time: "Night",
    family: "Floral Fruity",
    accords: ["Floral", "Fruity", "Warm"],
    top: "Cassis (Blackcurrant Syrup)",
    mid: "May Rose, Freesia",
    base: "Vanilla, Patchouli, Ambroxan, Woody Notes",
    price: 69
  },
  {
    id: 44,
    name: "Captain’s Ember",
    image: "norm5.png",
    images: ["norm5.png", "captainsea1.jpg", "captainsea2.jpg", "infoa.jpg"],
    description: "A concentrated attar version delivering warm amber sweetness and woody sensuality.",
    type: "Attar",
    inspiredBy: "Le Male Elixir",
    gender: "Male",
    season: "Autumn-Winter",
    time: "Night",
    family: "Amber Woody",
    accords: ["Sweet", "Amber", "Woody"],
    top: "Lavender, Mint",
    mid: "Vanilla, Benzoin",
    base: "Honey, Tonka Bean, Tobacco",
    price: 69
  },
  {
    id: 45,
    name: "Sabaya",
    image: "sabaya.png",
    images: ["sabaya.png", "sabyaa1.jpg", "sabyaa2.jpg", "infoa.jpg"],
    description: "A light and airy floral attar with herbal freshness, ideal for warm daytime wear.",
    type: "Attar",
    inspiredBy: "",
    gender: "Female",
    season: "Spring-Summer",
    time: "Day",
    family: "Floral",
    accords: ["Floral", "Herbal"],
    top: "Citrus",
    mid: "Green Notes",
    base: "Rose",
    price: 59
  },
  {
    id: 46,
    name: "Purple OUD",
    image: "norm4.png",
    images: ["norm4.png", "purpleoa1.jpg", "purpleoa2.jpg", "infoa.jpg"],
    description: "A spicy oriental oud fragrance with saffron warmth and woody depth for night-time wear.",
    type: "Attar",
    inspiredBy: "Dior Purple Oud",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Woody",
    accords: ["Oriental", "Woody", "Spicy"],
    top: "Pink Pepper, Orange",
    mid: "Saffron",
    base: "Agarwood (Oud)",
    price: 79
  },
  {
    id: 47,
    name: "Pulse Royale",
    image: "norm6.png",
    images: ["norm6.png", "pulsera1.jpg", "pulsera2.jpg", "infoa.jpg"],
    description: "A modern marine-sweet fragrance with spicy tobacco undertones, energetic and youthful.",
    type: "Attar",
    inspiredBy: "CR-7",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Aromatic Sweet",
    accords: ["Sweet", "Marine", "Sweet"],
    top: "Lavender, Cardamom, Artemisia, Bergamot",
    mid: "Tobacco, Cinnamon, Cedar, Iris",
    base: "Vanilla, Musk, Sandalwood, Amber",
    price: 69
  },
  {
    id: 48,
    name: "Invictus",
    image: "fresh marine.png",
    images: ["fresh marine.png", "invictusa1.jpg", "invictusa2.jpg", "infoa.jpg"],
    description: "A powerful fresh-marine fragrance with citrus brightness and woody amber depth.",
    type: "Attar",
    inspiredBy: "Paco Rabanne Invictus",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Marine Fresh",
    accords: ["Citrus", "Marine", "Aromatic"],
    top: "Sea Notes, Grapefruit, Mandarin Orange",
    mid: "Bay Leaf, Jasmine",
    base: "Ambergris, Guaiac Wood, Oakmoss, Patchouli",
    price: 69
  },
  {
    id: 49,
    name: "Aseel",
    image: "norm1.png",
    images: ["norm1.png", "aseela1.jpg", "aseela2.jpg", "infoa.jpg"],
    description: "A balanced woody-floral attar with herbal nuances and soft musky depth.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day/Night",
    family: "Woody Floral",
    accords: ["Woody", "Floral", "Herbal"],
    top: "Red Rose, Saffron",
    mid: "Sandalwood, Mint",
    base: "Agarwood (Oud), Musk",
    price: 69
  },
  {
    id: 50,
    name: "Fasli Gulab",
    image: "fasli gulab.png",
    images: ["fasli gulab.png", "fasliga1.jpg", "fasliga2.jpg", "infoa.jpg"],
    description: "A soft and powdery rose attar capturing the freshness of blooming garden roses.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Spring-Summer",
    time: "Day",
    family: "Floral",
    accords: ["Floral", "Powdery"],
    top: "Rose",
    mid: "",
    base: "",
    price: 69
  },
  {
    id: 51,
    name: "Aventus",
    image: "creed aventus.png",
    images: ["creed aventus.png", "aventusa1.jpg", "aventusa2.jpg", "infoa.jpg"],
    description: "A bold fruity-chypre fragrance with smoky woods and fresh pineapple character.",
    type: "Attar",
    inspiredBy: "Creed Aventus",
    gender: "Male",
    season: "All seasons",
    time: "Day/Night",
    family: "Chypre Fruity",
    accords: ["Fruity-Chypre", "Woody"],
    top: "Pineapple, Bergamot, Blackcurrant, Apple",
    mid: "Birch, Patchouli, Moroccan Jasmine, Rose",
    base: "Musk, Oakmoss, Ambergris, Vanille",
    price: 85
  },
  {
    id: 52,
    name: "Golden Blush",
    image: "female floral.png",
    images: ["female floral.png", "goldenba1.jpg", "goldenba2.jpg", "infoa.jpg"],
    description: "A delicate floral gourmand fragrance with creamy sweetness and soft freshness.",
    type: "Attar",
    inspiredBy: "Carolina Herrrera Good Girl Blush",
    gender: "Female",
    season: "Spring-Summer",
    time: "Day",
    family: "Floral Gourmand",
    accords: ["Floral", "Gourmand", "Fresh"],
    top: "Bergamot, Bitter Almond",
    mid: "Peony, Ylang-Ylang",
    base: "Vanilla, Coumarin",
    price: 69
  },
  {
    id: 54,
    name: "Fresh Horizon",
    image: "fresh eros.png",
    images: ["fresh eros.png", "freshha1.jpg", "freshha2.jpg", "infoa.jpg"],
    description: "A long-lasting attar version delivering sweet woody warmth with fresh aromatic highlights.",
    type: "Attar",
    inspiredBy: "Versace Eros",
    gender: "Male",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Woody",
    accords: ["Woody", "Oriental", "Sweet"],
    top: "Mint, Green Apple, Lemon",
    mid: "Tonka Bean, Ambroxan, Geranium",
    base: "Vanilla, Cedar, Vetiver, Oakmoss",
    price: 69
  },
  {
    id: 56,
    name: "Velvet Night",
    image: "sweet gourmond.png",
    images: ["sweet gourmond.png", "velvetna1.jpg", "velvetna2.jpg", "infoa.jpg"],
    description: "A concentrated attar version of a rich gourmand-oriental scent with coffee sweetness and creamy vanilla depth.",
    type: "Attar",
    inspiredBy: "YSL Black Opium",
    gender: "Female",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Gourmand",
    accords: ["Gourmand", "Oriental", "Sweet"],
    top: "Pear, Pink Pepper, Orange Blossom",
    mid: "Coffee, Jasmine, Bitter Almond, Licorice",
    base: "Vanilla, Patchouli, Cedar, Cashmere Wood",
    price: 69
  },
  {
    id: 57,
    name: "Titanium",
    image: "titanium.png",
    images: [
      "titanium.png", 
      "titanium1.png", 
      "titanium2.png", 
      "titanium3.png", 
      "titanium4.png", 
      "titanium5.png", 
      "titanium6.png", 
      "titanium7.png", 
      "titanium100.png"
    ],
    description: "A fresh aromatic-fruity fragrance offering a clean, energetic profile suitable for everyday wear.",
    type: "Perfume",
    inspiredBy: "",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Aromatic Fresh",
    accords: ["Aromatic","Marine", "Aquatic"],
    top: "Pineapple,Mandrin orange",
    mid: "Marine note, Patchouli & Dry Amber",
    base: "Oakmoss & Musk ",
    price: 449
  },
  {
    id: 58,
    name: "Titanium",
    image: "fresh marine.png",
    images: ["fresh marine.png", "titaniuma1.jpg", "titaniuma2.jpg", "infoa.jpg"],
    description: "A long-lasting attar version of a crisp aromatic fragrance with fruity freshness and woody warmth.",
    type: "Attar",
    inspiredBy: "Titanium Ajmal",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Aromatic Fresh",
    accords: ["Aromatic", "Fruity"],
    top: "Citrus, Fruity Notes",
    mid: "Fresh Spicy Notes",
    base: "Woody Notes, Musk",
    price: 89
  },
  {
    id: 59,
    name: "White OUD",
    image: "norm2.png",
    images: ["norm2.png", "whiteoa1.jpg", "whiteoa2.jpg", "infoa.jpg"],
    description: "A refined oud fragrance softened by fresh florals and subtle tobacco warmth.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Floral",
    accords: ["Fresh", "Floral"],
    top: "Artemisia, Lemon, Orange",
    mid: "Freesia, Patchouli, Black Currant",
    base: "Tobacco, Amber, Musk",
    price: 79
  },
  {
    id: 61,
    name: "Most Wanted",
    image: "norm2.png",
    images: ["norm2.png", "mostwa1.jpg", "mostwa2.jpg", "infoa.jpg"],
    description: "A concentrated attar interpretation delivering intense sweetness and woody amber richness.",
    type: "Attar",
    inspiredBy: "AZ The Most Wanted",
    gender: "Male",
    season: "Autumn-Winter",
    time: "Night",
    family: "Amber Woody",
    accords: ["Amber", "Woody", "Sweet"],
    top: "Cardamom",
    mid: "Toffee",
    base: "Amberwood",
    price: 79
  },
  {
    id: 63,
    name: "BLU Ember",
    image: "fresh_auqatic.png",
    images: ["fresh_auqatic.png", "bluea1.jpg", "bluea2.jpg", "infoa.jpg"],
    description: "A long-lasting attar version offering aquatic freshness balanced with aromatic warmth.",
    type: "Attar",
    inspiredBy: "Ajmal BLU",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Aquatic",
    accords: ["Fresh", "Aquatic", "Aromatic"],
    top: "Watermelon, Bergamot, Lavender",
    mid: "Lotus, Jasmine",
    base: "Musk, Amber, Sandalwood",
    price: 69
  },
  {
    id: 65,
    name: "Caramel OUD",
    image: "sweet chocolate gourmond.png",
    images: ["sweet chocolate gourmond.png", "carameloa1.jpg", "carameloa2.jpg", "infoa.jpg"],
    description: "A rich attar version offering intense caramel sweetness balanced with smoky oud depth.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Gourmand Woody",
    accords: ["Gourmand", "Woody"],
    top: "Chocolate, Honey",
    mid: "Rose, Oud, Amber",
    base: "Vanilla, Powdery Notes",
    price: 69
  },
  {
    id: 66,
    name: "Shanaya",
    image: "norm4.png",
    images: ["norm4.png", "shanaya1.jpg", "shanaya2.jpg", "info.jpg"],
    description: "A graceful woody-floral fragrance accented with amber warmth and soft sweetness.",
    type: "Attar",
    inspiredBy: "",
    gender: "Female",
    season: "All seasons",
    time: "Day/Night",
    family: "Woody Floral",
    accords: ["Woody", "Floral", "Amber"],
    top: "Rose, Saffron, Pimento",
    mid: "Agarwood (Oud), Caramel, Floral Notes",
    base: "Resins, Amber, Musk",
    price: 89
  },
  {
    id: 67,
    name: "Fresh Impact",
    image: "fresh marine.png",
    images: ["fresh marine.png", "freshia1.jpg", "freshia2.jpg", "infoa.jpg"],
    description: "A vibrant citrus-spicy fragrance with green freshness and refined woody depth.",
    type: "Attar",
    inspiredBy: "LV Imagination",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Spicy",
    accords: ["Citrus", "Fresh-Spicy", "Green"],
    top: "Citron, Calabrian Bergamot, Orange",
    mid: "Ginger, Tunisian Neroli, Cinnamon",
    base: "Tea, Ambroxan, Guaiac Wood, Olibanum",
    price: 69
  },

  {
    id: 70,
    name: "br 540",
    image: "br 540.png",
    images: [
      "br 540.png", 
      "br 5401.png", 
      "br 5402.png", 
      "br 5403.png", 
      "br 5404.png", 
      "br 5405.png", 
      "br 5406.png", 
      "br 5407.png", 
      "br 540100.png"
    ],
    description: "A luxurious ambery fragrance with saffron warmth, airy sweetness, and radiant depth.",
    type: "Perfume",
    inspiredBy: "MFK Baccarat Rouge 540",
    gender: "Unisex",
    season: "All seasons",
    time: "Day/Night",
    family: "Amber Woody",
    accords: ["Amber", "Sweet", "Woody"],
    top: "Saffron, Jasmine",
    mid: "Amberwood, Ambergris",
    base: "Fir Resin, Cedar",
    price: 399
  },
  {
    id: 71,
    name: "BR 540",
    image: "smoky.png",
    images: ["smoky.png", "br540a1.jpg", "br540a2.jpg", "infoa.jpg"],
    description: "A concentrated attar version of a radiant ambery fragrance with airy sweetness and luxurious warmth.",
    type: "Attar",
    inspiredBy: "MFK Baccarat Rouge 540",
    gender: "Unisex",
    season: "All seasons",
    time: "Day/Night",
    family: "Amber Woody",
    accords: ["Amber", "Sweet", "Woody"],
    top: "Saffron, Jasmine",
    mid: "Amberwood, Ambergris",
    base: "Fir Resin, Cedar",
    price: 89
  },
  {
    id: 73,
    name: "Qahwa",
    image: "sweet gourmond.png",
    images: ["sweet gourmond.png", "qahwaa1.jpg", "qahwaa2.jpg", "infoa.jpg"],
    description: "A long-lasting attar rendition delivering bold coffee warmth blended with sweet spices.",
    type: "Attar",
    inspiredBy: "Khamra Qahwa",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Gourmand",
    accords: ["Spicy", "Coffee", "Sweet"],
    top: "Ginger, Cinnamon, Cardamom",
    mid: "Praline, Candied Fruits",
    base: "Coffee, Tonka Bean, Vanilla",
    price: 89
  },
  {
    id: 75,
    name: "Obsidian OUD",
    image: "smoky.png",
    images: ["smoky.png", "obsidianoa1.jpg", "obsidianoa2.jpg", "infoa.jpg"],
    description: "A concentrated attar version offering intense fruity sweetness layered over smoky oud.",
    type: "Attar",
    inspiredBy: "Oud maracuja",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Fruity Woody",
    accords: ["Fruity-Chypre", "Woody"],
    top: "Passionfruit, Saffron, Turkish Rose",
    mid: "Oud, Patchouli, Benzoin",
    base: "Leather, Amber, Vanilla",
    price: 79
  },
  {
    id: 76,
    name: "Dark Rebel",
    image: "smoky.png",
    images: ["dark rebel.png", "darkra1.jpg", "darkra2.jpg", "infoa.jpg"],
    description: "A dark woody-spicy fragrance with smoky oud and warm amber undertones.",
    type: "Attar",
    inspiredBy: "TF OUD wood",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Spicy",
    accords: ["Woody", "Spicy", "Oriental"],
    top: "Cardamom, Sichuan Pepper",
    mid: "Vanilla",
    base: "Tonka Bean, Oud, Vetiver, Amber",
    price: 89
  },
  {
    id: 77,
    name: "Woody OUD",
    image: "woodyoudp.png",
    images: ["woodyoudp.png", "woodyoa1.jpg", "woodyoa2.jpg", "infoa.jpg"],
    description: "A powerful woody-oriental attar with spicy warmth and deep resinous oud character.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Oriental",
    accords: ["Woody", "Spicy", "Oriental"],
    top: "Cardamom, Sichuan Pepper",
    mid: "Vanilla",
    base: "Tonka Bean, Oud, Vetiver, Amber",
    price: 279
  },
  {
    id: 78,
    name: "Musk Abiyad",
    image: "norm1.png",
    images: ["norm1.png", "muskaa1.jpg", "muskaa2.jpg", "infoa.jpg"],
    description: "A soft and clean white musk fragrance with powdery floral nuances for everyday wear.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day",
    family: "Musky",
    accords: ["Musky", "Powdery", "Floral"],
    top: "Rose, White Musk",
    mid: "Balsamic, Powdery Notes",
    base: "Musk, Sandalwood",
    price: 89
  },
  {
    id: 79,
    name: "Midnight",
    image: "smoky, oudy, spicy.png",
    images: ["smoky, oudy, spicy.png", "midnighta1.jpg", "midnighta2.jpg", "infoa.jpg"],
    description: "A fresh spicy-woody fragrance with citrus brightness and aromatic warmth for evening wear.",
    type: "Attar",
    inspiredBy: "",
    gender: "Male",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Spicy",
    accords: ["Woody", "Fresh Spicy", "Citrus"],
    top: "Bergamot, Lavender",
    mid: "Geranium, Orange Blossom",
    base: "Patchouli, Woody Notes",
    price: 89
  },
  {
    id: 80,
    name: "Musk Safi",
    image: "musk.png",
    images: ["musk.png", "musksa1.jpg", "musksa2.jpg", "infoa.jpg"],
    description: "A clean musky fragrance balanced with soft florals and smooth woody undertones.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day",
    family: "Musky Floral",
    accords: ["Musky", "Woody", "Floral"],
    top: "Lily of the Valley",
    mid: "White Musk",
    base: "Sandalwood, Amber",
    price: 89
  },
  {
    id: 81,
    name: "Eternal Sauvage",
    image: "dior sauvage.png",
    images: ["dior sauvage.png", "eternalsa1.jpg", "eternalsa2.jpg", "infoa.jpg"],
    description: "A fresh spicy fragrance with aromatic herbs and ambroxan depth, powerful and versatile.",
    type: "Attar",
    inspiredBy: "Dior Sauvage",
    gender: "Male",
    season: "All seasons",
    time: "Day/Night",
    family: "Fresh Spicy",
    accords: ["Fresh", "Spicy-Oriental"],
    top: "Calabrian Bergamot, Pepper",
    mid: "Sichuan Pepper, Lavender, Vetiver",
    base: "Ambroxan, Cedar, Labdanum",
    price: 69
  },
  {
    id: 82,
    name: "Dahnal OUD",
    image: "dahnaloud.png",
    images: ["dahnaloud.png", "dahnaloa1.jpg", "dahnaloa2.jpg", "infoa.jpg"],
    description: "A raw and powerful oud attar with honeyed warmth and deep woody intensity.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Oriental",
    accords: ["Woody", "Honey", "Spicy"],
    top: "Oud",
    mid: "",
    base: "",
    price: 99
  },
  {
    id: 83,
    name: "Eternal White",
    image: "eternal white.png",
    images: [
      "eternal white.png", 
      "eternal white1.png", 
      "eternal white2.png", 
      "eternal white3.png", 
      "eternal white4.png", 
      "eternal white5.png", 
      "eternal white6.png", 
      "eternal_white7.png", 
      "eternal white100.png"
    ],
    description: "A clean citrus-woody fragrance with aromatic freshness and smooth leather undertones.",
    type: "Perfume",
    inspiredBy: "Lacoste White",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Woody",
    accords: ["Citrus", "Woody", "Aromatic"],
    top: "Grapefruit, Rosemary, Cardamom",
    mid: "Ylang-Ylang, Tuberose",
    base: "Suede, Cedar, Leather, Vetiver",
    price: 449
  },
  {
    id: 84,
    name: "Eternal White",
    image: "lacoste w.png",
    images: ["lacoste w.png", "eternalwa1.jpg", "eternalwa2.jpg", "infoa.jpg"],
    description: "A long-lasting attar version delivering crisp citrus freshness and woody elegance.",
    type: "Attar",
    inspiredBy: "Lacoste White",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Woody",
    accords: ["Citrus", "Woody", "Aromatic"],
    top: "Grapefruit, Rosemary, Cardamom",
    mid: "Ylang-Ylang, Tuberose",
    base: "Suede, Cedar, Leather, Vetiver",
    price: 99
  },
  {
    id: 87,
    name: "Intense Suede",
    image: "spicy.png",
    images: ["spicy.png", "intensesa1.jpg", "intensesa2.jpg", "infoa.jpg"],
    description: "A rich vanilla-amber fragrance with suede softness and warm spicy accents for intense evening wear.",
    type: "Attar",
    inspiredBy: "Armani SWY intensely",
    gender: "Male",
    season: "Autumn-Winter",
    time: "Night",
    family: "Amber Vanilla",
    accords: ["Vanilla", "Sweet", "Amber"],
    top: "Pink Pepper, Juniper, Violet",
    mid: "Toffee, Cinnamon, Lavender, Sage",
    base: "Vanilla, Amber, Tonka Bean, Suede",
    price: 79
  },
  {
    id: 89,
    name: "Aurum",
    image: "aurum.png",
    images: ["aurum.png", "auruma1.jpg", "auruma2.jpg", "infoa.jpg"],
    description: "A concentrated attar version offering creamy white florals with soft fruity sweetness.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day/Night",
    family: "Floral, Fresh",
    accords: ["White Floral", "Fruity", "Powdery"],
    top: "Raspberry, Lemon",
    mid: "Orange Blossom, Gardenia, Jasmine",
    base: "Vanilla, Amber, Musk",
    price: 129
  },
  {
    id: 90,
    name: "Blue OUD",
    image: "blue oud.png",
    images: [
      "blue_oud.png", 
      "blue_oud1.png", 
      "blue_oud2.png", 
      "blue_oud3.png", 
      "blue_oud4.png", 
      "blue_oud5.png", 
      "blue_oud6.png", 
      "blue_oud7.png", 
      "blue_oud100.png"
    ],
    description: "A bold oud-leather fragrance with smoky depth and earthy patchouli richness.",
    type: "Perfume",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Leather Woody",
    accords: ["Oud", "Leather", "Patchouli"],
    top: "Blue Lily, Oud",
    mid: "Patchouli, Leather",
    base: "Amber, Tobacco",
    price: 599
  },
  {
    id: 91,
    name: "Blue OUD",
    image: "blueoud.png",
    images: ["blueoud.png", "blueoa1.jpg", "blueoa2.jpg", "infoa.jpg"],
    description: "A concentrated attar delivering intense oud-leather richness with smoky warmth.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Leather Woody",
    accords: ["Oud", "Leather", "Patchouli"],
    top: "Blue Lily, Oud",
    mid: "Patchouli, Leather",
    base: "Amber, Tobacco",
    price: 175
  },
  {
    id: 92,
    name: "Musk Rijali",
    image: "muskrijali.png",
    images: ["muskrijali.png", "muskr1.jpg", "muskr2.jpg", "info.jpg"],
    description: "A refined musky fragrance with subtle sweetness and gentle floral warmth.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day",
    family: "Musky",
    accords: ["Musky", "Subtle Sweet", "Floral"],
    top: "Musk, Bergamot",
    mid: "Jasmine, Saffron",
    base: "Oud, Amber, Vanilla",
    price: 115
  },
  {
    id: 93,
    name: "Musk Rijali Premium",
    image: "muskrijp.png",
    images: ["muskrijp.png", "muskrpa1.jpg", "muskrpa2.jpg", "infoa.jpg"],
    description: "A premium musky attar with enhanced smoothness, sweetness, and long-lasting warmth.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day",
    family: "Musky",
    accords: ["Musky", "Subtle Sweet", "Floral"],
    top: "Musk, Bergamot",
    mid: "Jasmine, Saffron",
    base: "Oud, Amber, Vanilla",
    price: 199
  },
  {
    id: 94,
    name: "OUD Al Shams",
    image: "ouodalshams.png",
    images: ["ouodalshams.png", "oudasa1.jpg", "oudasa2.jpg", "infoa.jpg"],
    description: "A warm spicy-vanilla oud fragrance with amber richness and smooth woody depth.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Spicy",
    accords: ["Spicy", "Vanilla", "Amber"],
    top: "Rosemary, Spicy Notes",
    mid: "Amber, Blackberry",
    base: "Cashmere Wood, Vanilla",
    price: 199
  },
 
  {
    id: 97,
    name: "Black OUD",
    image: "black.png",
    images: ["black.png", "blackoa1.jpg", "blackoa2.jpg", "infoa.jpg"],
    description: "A smoky woody oud fragrance with leathery depth and earthy warmth.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Smoky",
    accords: ["Woody", "Smoky"],
    top: "Lemon, Mandarin, Oud, Saffron",
    mid: "Rose, Patchouli",
    base: "Leather, Sandalwood, White Musk, Guaiacwood",
    price: 149
  },
  {
    id: 98,
    name: "Mukhallat OUD",
    image: "prem7.png",
    images: ["prem7.png", "mukhallatoa1.jpg", "mukhallatoa2.jpg", "infoa.jpg"],
    description: "A floral-woody oud blend with spicy warmth and smooth musky undertones.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Floral",
    accords: ["Floral", "Woody", "Spicy"],
    top: "Floral Notes, Spicy Notes",
    mid: "Fruity Notes, Musk",
    base: "Musk, Woody Notes",
    price: 249
  },
  {
    id: 99,
    name: "Mukhallat Rashid",
    image: "prem1.png",
    images: ["prem1.png", "mukhallatra1.jpg", "mukhallatra2.jpg", "infoa.jpg"],
    description: "A complex leathery-woody fragrance with floral spices and earthy depth.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Leather Woody",
    accords: ["Leathery", "Woody", "Spicy Floral"],
    top: "Saffron, Clove, Sage",
    mid: "Rose, Geranium, Henna",
    base: "Oud, Vetiver, Soil Tincture, Patchouli",
    price: 249
  },

  {
    id: 102,
    name: "Mukhallat Maliky",
    image: "oudshay.png",
    images: ["oudshay.png", "mukhallatma1.jpg", "mukhallatma2.jpg", "infoa.jpg"],
    description: "A warm woody-amber fragrance enriched with spices and smooth oriental depth.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Amber",
    accords: ["Woody", "Warm Spicy", "Amber"],
    top: "Warm Spices, Soft Florals",
    mid: "Oud, Amber, Floral Accords",
    base: "Musk, Woods, Resinous Warmth",
    price: 249
  },
  {
    id: 103,
    name: "Musk Tahara",
    image: "musktahara.png",
    images: ["musktahara.png", "muskt1.jpg", "muskt2.jpg", "info.jpg"],
    description: "A pure and clean white musk fragrance with soft powdery freshness, ideal for daily wear.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day",
    family: "Musky Clean",
    accords: ["Fresh", "Musky", "Powdery"],
    top: "White Musk",
    mid: "",
    base: "",
    price: 99
  },

  {
    id: 106,
    name: "Kuwaiti OUD",
    image: "kuwaitioud.png",
    images: ["kuwaitioud.png", "kuwaitioa1.jpg", "kuwaitioa2.jpg", "infoa.jpg"],
    description: "A rich and spicy oud fragrance with earthy warmth and smooth vanilla undertones.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Spicy",
    accords: ["Woody", "Spicy", "Earthy"],
    top: "Rosemary, Cardamom, Ginger",
    mid: "Saffron, Jasmine, Tonka Bean",
    base: "Amber, Sandalwood, Vanilla, Oud, Patchouli, Musk",
    price: 149
  },
  {
    id: 107,
    name: "Kuwaiti OUD Premium",
    image: "kuwatioudp.png",
    images: ["kuwatioudp.png", "kuwaitiopa1.jpg", "kuwaitiopa2.jpg", "infoa.jpg"],
    description: "A premium and more intense interpretation of Kuwaiti Oud with enhanced depth and longevity.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Spicy",
    accords: ["Woody", "Spicy", "Earthy"],
    top: "Rosemary, Cardamom, Ginger",
    mid: "Saffron, Jasmine, Tonka Bean",
    base: "Amber, Sandalwood, Vanilla, Oud, Patchouli, Musk",
    price: 279
  },
  {
    id: 108,
    name: "Mysore Sandal",
    image: "mysandalp.png",
    images: ["mysandalp.png", "mysorea1.jpg", "mysorea2.jpg", "infoa.jpg"],
    description: "A pure and creamy sandalwood fragrance sourced from Mysore, smooth, meditative, and timeless.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day",
    family: "Woody",
    accords: ["Woody", "Vanilla", "Musky"],
    top: "Sandalwood from Mysore",
    mid: "",
    base: "",
    price: 279
  },
  {
    id: 109,
    name: "Seufi OUD",
    image: "seufioudp.png",
    images: ["seufioudp.png", "seufioa1.jpg", "seufioa2.jpg", "infoa.jpg"],
    description: "A floral-woody oriental fragrance with musky softness and rich Indian oud depth.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Woody",
    accords: ["Floral", "Woody", "Oriental"],
    top: "Mitti",
    mid: "Musk",
    base: "Agarwood (Indian Oud)",
    price: 299
  },
  {
    id: 110,
    name: "Indian OUD",
    image: "oudindiap.jpg",
    images: ["oudindiap.jpg", "indianoa1.jpg", "indianoa2.jpg", "infoa.jpg"],
    description: "A raw and intense Indian oud fragrance with smoky depth and earthy richness.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Smoky",
    accords: ["Woody", "Oriental", "Smoky"],
    top: "Agarwood (Indian Oud)",
    mid: "",
    base: "",
    price: 499
  },
  {
    id: 111,
    name: "Thailand OUD",
    image: "oudthaip.jpg",
    images: ["oudthaip.jpg", "thailandoa1.jpg", "thailandoa2.jpg", "infoa.jpg"],
    description: "A refined Thai oud fragrance with spicy warmth and subtle sweetness.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Oriental",
    accords: ["Woody", "Oriental Spicy", "Subtle Sweet"],
    top: "Agarwood (Thailand Oud)",
    mid: "",
    base: "",
    price: 499
  },
  {
    id: 112,
    name: "Cambodian OUD",
    image: "oudcombodip.jpg",
    images: ["oudcombodip.jpg", "cambodianoa1.jpg", "cambodianoa2.jpg", "infoa.jpg"],
    description: "A smooth Cambodian oud with mossy undertones and rich oriental warmth.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Oriental",
    accords: ["Woody", "Oriental", "Mossy"],
    top: "Agarwood (Cambodian Oud)",
    mid: "",
    base: "",
    price: 499
  },

  {
    id: 114,
    name: "Sandaliya",
    image: "sandaliyap.jpg",
    images: ["sandaliyap.jpg", "sandaliyaa1.jpg", "sandaliyaa2.jpg", "infoa.jpg"],
    description: "A deep sandalwood-centric fragrance with earthy spice and woody warmth.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day",
    family: "Woody Earthy",
    accords: ["Citrus Spicy", "Earthy", "Woody"],
    top: "Sandalwood",
    mid: "",
    base: "",
    price: 899
  },
  {
    id: 115,
    name: "Dehnal OUD Combodi Qadim",
    image: "daocombodip.jpg",
    images: ["daocombodip.jpg", "dehnalca1.jpg", "dehnalca2.jpg", "infoa.jpg"],
    description: "An aged Cambodian oud attar offering deep honeyed richness and elegant woody warmth.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Oriental",
    accords: ["Woody", "Honey", "Spicy", "Elegant"],
    top: "Aged Cambodian Oud",
    mid: "",
    base: "",
    price: 899
  },
  {
    id: 116,
    name: "Dahnal OUD Hindi Qadim",
    image: "daoindianp.jpg",
    images: ["daoindianp.jpg", "dehnalha1.jpg", "dehnalha2.jpg", "infoa.jpg"],
    description: "An aged Indian oud fragrance showcasing deep woody intensity with honeyed warmth and natural spice.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Oriental",
    accords: ["Woody", "Honey", "Spicy"],
    top: "Aged Indian Oud",
    mid: "",
    base: "",
    price: 899
  },
  {
    id: 117,
    name: "Fire OUD",
    image: "fire oud.png",
    images: [
      "fire_oud.png", 
      "fire_oud1.png", 
      "fire_oud2.png", 
      "fire_oud3.png", 
      "fire_oud4.png", 
      "fire_oud5.png", 
      "fire_oud6.png", 
      "fire_oud7.png", 
      "fire_oud100.png"
    ],
    description: "A bold woody-leather fragrance with aromatic freshness and smoky warmth.",
    type: "Perfume",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Leather Woody",
    accords: ["Woody", "Leather", "Aromatic"],
    top: "Geranium, Leather",
    mid: "Cedar, Patchouli",
    base: "Moss, Musk, Amber",
    price: 599
  },
  {
    id: 118,
    name: "Fire OUD",
    image: "fireoud.png",
    images: ["fireoud.png", "fireoa1.jpg", "fireoa2.jpg", "infoa.jpg"],
    description: "A concentrated attar version delivering intense leather-woody richness with smoky depth.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Leather Woody",
    accords: ["Woody", "Leather", "Aromatic"],
    top: "Geranium, Leather",
    mid: "Cedar, Patchouli",
    base: "Moss, Musk, Amber",
    price: 149
  },
  {
    id: 119,
    name: "Ruh Khus",
    image: "ruhkhusp.jpg",
    images: ["ruhkhusp.jpg", "ruhkhusa1.jpg", "ruhkhusa2.jpg", "infoa.jpg"],
    description: "A pure vetiver fragrance offering earthy freshness, green herbal tones, and cooling depth.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Summer",
    time: "Day",
    family: "Green Earthy",
    accords: ["Fresh", "Green Herbal", "Earthy"],
    top: "Vetiver (Khus)",
    mid: "",
    base: "",
    price: 599
  },
  {
    id: 120,
    name: "Fume Vanille",
    image: "fume vanille.png",
    images: [
      "fume vanille.png", 
      "fume vanille1.png", 
      "fume vanille2.png", 
      "fume vanille3.png", 
      "fume vanille4.png", 
      "fume vanille5.png", 
      "fume vanille6.png", 
      "fume_vanille7.png", 
      "fume vanille100.png"
    ],
    description: "A warm oriental gourmand fragrance blending tobacco spice with creamy vanilla sweetness.",
    type: "Perfume",
    inspiredBy: "Tobacco Vanille",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Gourmand",
    accords: ["Oriental", "Gourmand", "Smoky"],
    top: "Tobacco Leaf, Spicy Notes",
    mid: "Vanilla, Cacao, Tonka Bean, Tobacco Blossom",
    base: "Dried Fruits, Woody Notes",
    price: 449
  },
  {
    id: 121,
    name: "Fume Vanille",
    image: "smokysweet.png",
    images: ["smokysweet.png", "fumeva1.jpg", "fumeva2.jpg", "infoa.jpg"],
    description: "A rich attar version delivering deep vanilla sweetness and smoky tobacco warmth.",
    type: "Attar",
    inspiredBy: "Tobacco Vanille",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Gourmand",
    accords: ["Oriental", "Gourmand", "Smoky"],
    top: "Tobacco Leaf, Spicy Notes",
    mid: "Vanilla, Cacao, Tonka Bean, Tobacco Blossom",
    base: "Dried Fruits, Woody Notes",
    price: 99
  },
  {
    id: 122,
    name: "Al Dahab",
    image: "aldahab.png",
    images: ["aldahab.png", "aldahaba1.jpg", "aldahaba2.jpg", "infoa.jpg"],
    description: "A luxurious fruity-floral fragrance with woody sweetness and golden warmth.",
    type: "Attar",
    inspiredBy: "Wisal Dahab",
    gender: "Female",
    season: "Autumn-Winter",
    time: "Night",
    family: "Floral Woody",
    accords: ["Dark Wood", "Sweet", "Floral"],
    top: "Pear, Apple, Peach, Grapefruit, Mandarin Orange",
    mid: "Rose, Orchid, Jasmine, Geranium",
    base: "Sandalwood, Musk, Cedar, Patchouli",
    price: 129
  },
  {
    id: 123,
    name: "Eternal Elixir",
    image: "spicy.png",
    images: ["spicy.png", "eternalela1.jpg", "eternalela2.jpg", "infoa.jpg"],
    description: "A bold spicy-woody fragrance with aromatic lavender and rich resinous warmth.",
    type: "Attar",
    inspiredBy: "Sauvage Elixir",
    gender: "Male",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Spicy",
    accords: ["Woody", "Floral", "Spicy"],
    top: "Nutmeg, Cinnamon, Cardamom, Grapefruit",
    mid: "Lavender",
    base: "Licorice, Sandalwood, Amber, Patchouli, Haitian Vetiver",
    price: 89
  },

  {
    id: 127,
    name: "Rose OUD",
    image: "roseoud.png",
    images: ["roseoud.png", "roseouda1.jpg", "roseouda2.jpg", "infoa.jpg"],
    description: "A concentrated attar version highlighting the richness of rose layered over oud.",
    type: "Attar",
    inspiredBy: "OUD And Roses",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Floral",
    accords: ["Woody", "Oriental", "Citrus"],
    top: "Rose",
    mid: "Rose",
    base: "Agarwood (Oud)",
    price: 99
  },
  {
    id: 128,
    name: "Mafia Oud",
    image: "blueoud.png",
    images: ["blueoud.png", "mafiaouda1.jpg", "mafiaouda2.jpg", "infoa.jpg"],
    description: "A dark smoky oud fragrance with earthy woods and subtle fruity undertones.",
    type: "Attar",
    inspiredBy: "Mafia OUD",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Smoky",
    accords: ["Woody", "Oriental", "Smoky"],
    top: "Oud, Musk, Patchouli",
    mid: "Sandalwood, Vetiver, Vanilla",
    base: "Woody, Smoky, Fruity, Earthy",
    price: 149
  },
  {
    id: 129,
    name: "Badee Al OUD",
    image: "all.png",
    images: ["all.png", "badeeoa1.jpg", "badeeoa2.jpg", "infoa.jpg"],
    description: "A modern spicy-oud fragrance blending aromatic freshness with warm woody richness.",
    type: "Attar",
    inspiredBy: "Badee Al OUD",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Spicy",
    accords: ["Woody", "Warm Spicy", "Fresh Spicy"],
    top: "Saffron, Nutmeg, Lavender",
    mid: "Oud, Patchouli",
    base: "Oud, Patchouli, Musk",
    price: 99
  },
  {
    id: 130,
    name: "Arabian Tonka",
    image: "oudriz.png",
    images: ["oudriz.png", "arabiantonka1.jpg", "arabiantonka2.jpg", "infoa.jpg"],
    description: "A rich gourmand-oriental fragrance with sweet tonka bean and warm amber depth.",
    type: "Attar",
    inspiredBy: "Arabian Tonka",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Gourmand",
    accords: ["Oriental", "Gourmand", "Woody"],
    top: "Saffron, Bergamot",
    mid: "Oud, Bulgarian Rose",
    base: "Tonka Bean, Sugar Cane, Amber, White Musk, Oakmoss",
    price: 99
  },
  {
    id: 131,
    name: "Musk Rose",
    image: "muskrose.png",
    images: ["muskrose.png", "muskrosea1.jpg", "muskrosea2.jpg", "infoa.jpg"],
    description: "A romantic floral-musky fragrance where fresh roses blend with soft spices and creamy woods.",
    type: "Attar",
    inspiredBy: "Musk Rose",
    gender: "Unisex",
    season: "All seasons",
    time: "Day",
    family: "Floral Musky",
    accords: ["Floral", "Spicy", "Musky"],
    top: "Bergamot, Peach, Apple, Pear",
    mid: "Cyclamen, Freesia, Rose",
    base: "Sandalwood, Cedarwood, Vanilla, Amber, Musk",
    price: 99
  },

  {
    id: 133,
    name: "Al Lail",
    image: "prem9.png",
    images: ["prem9.png", "allaila1.jpg", "allaila2.jpg", "infoa.jpg"],
    description: "A sensual fruity-floral fragrance with oud richness and incense warmth, elegant and mysterious.",
    type: "Attar",
    inspiredBy: "Wisal Lail",
    gender: "Female",
    season: "Autumn-Winter",
    time: "Night",
    family: "Floral Woody",
    accords: ["Fruity", "Floral", "Woody"],
    top: "Blackcurrant, Apricot, Freesia",
    mid: "Rose, Patchouli, Osmanthus",
    base: "Musk, Oud, Frankincense",
    price: 129
  },
  {
    id: 134,
    name: "Rooh Gulab",
    image: "rooh gulab.png",
    images: ["rooh gulab.png", "roohgula1.jpg", "roohgula2.jpg", "infoa.jpg"],
    description: "A pure and natural rose distillation capturing the essence of fresh blooming roses.",
    type: "Attar",
    inspiredBy: "Rooh Gulab",
    gender: "Unisex",
    season: "Spring-Summer",
    time: "Day",
    family: "Floral",
    accords: ["Rose Floral"],
    top: "Rose",
    mid: "",
    base: "",
    price: 129
  },
  {
    id: 135,
    name: "Tobacco OUD",
    image: "black.png",
    images: ["black.png", "tobaccoouda1.jpg", "tobaccoouda2.jpg", "infoa.jpg"],
    description: "A dark and intense blend of tobacco smoke and oud with spicy warmth and resinous sweetness.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Smoky",
    accords: ["Woody", "Leathery", "Tobacco"],
    top: "Whiskey",
    mid: "Spicy Notes, Cinnamon, Coriander",
    base: "Tobacco, Oud, Incense, Sandalwood, Patchouli, Benzoin, Vanilla, Cedar",
    price: 129
  },
  {
    id: 136,
    name: "Arabian OUD",
    image: "prem1.png",
    images: ["prem1.png", "arabianouda1.jpg", "arabianouda2.jpg", "infoa.jpg"],
    description: "A smooth and powdery oud fragrance with warm spices and oriental depth.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Woody",
    accords: ["Woody", "Powdery", "Warm Spicy"],
    top: "",
    mid: "",
    base: "",
    price: 129
  },
  {
    id: 137,
    name: "Bin Sheikh",
    image: "prem8.png",
    images: ["prem8.png", "binsheikha1.jpg", "binsheikha2.jpg", "infoa.jpg"],
    description: "A rich amber-oud fragrance with floral sweetness and smoky oriental warmth.",
    type: "Attar",
    inspiredBy: "AM BIN SHEIKH",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Amber Oriental",
    accords: ["Amber", "Oud", "Sweet"],
    top: "Saffron, Rose, Oakmoss, Lavender, Citruses",
    mid: "Sugar, Bakhoor, Jasmine, Orchid, Violet",
    base: "Oud, Amber, Ambroxan, Patchouli, White Musk",
    price: 129
  },
  {
    id: 140,
    name: "Silk Oud",
    image: "silkoud.png",
    images: ["silkoud.png", "silkouda1.jpg", "silkouda2.jpg", "infoa.jpg"],
    description: "A refined floral-woody oud fragrance with herbal softness and smooth resinous depth.",
    type: "Attar",
    inspiredBy: "MFK Silk OUD",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Floral",
    accords: ["Herbal", "Woody", "Floral"],
    top: "Bulgarian Rose, Chamomile, Bergamot",
    mid: "Guaiac Wood, Hedione",
    base: "Oud, Papyrus",
    price: 99
  },
  {
    id: 141,
    name: "Shamama",
    image: "prem9.png",
    images: ["prem9.png", "shamamaa1.jpg", "shamamaa2.jpg", "infoa.jpg"],
    description: "A traditional complex attar blending woods, florals, and powdery warmth with deep heritage character.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Woody",
    accords: ["Woody", "Floral", "Powdery"],
    top: "Grass, Mint",
    mid: "Floral notes, Honey, Sea notes",
    base: "Smoke, Sandalwood",
    price: 249
  },
  {
    id: 142,
    name: "Al Wadi",
    image: "prem6.png",
    images: ["prem6.png", "ruhalwadia1.jpg", "ruhalwadia2.jpg", "infoa.jpg"],
    description: "A powerful aromatic-leather fragrance with oud richness and spicy freshness.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Leather Aromatic",
    accords: ["Woody", "Aromatic", "Leather"],
    top: "Sicilian Bergamot, Pink Pepper, Davana",
    mid: "Oud, White Amber, Rosemary",
    base: "Leather, Musk, Haitian Vetiver",
    price: 129
  },
  {
    id: 144,
    name: "Ombre",
    image: "blueoud.png",
    images: ["blueoud.png", "ombrea1.jpg", "ombrea2.jpg", "infoa.jpg"],
    description: "A deep and intense attar version with smoky oud, amber richness, and spicy warmth.",
    type: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Night",
    family: "Leathry Spicy",
    accords: ["Leather", "Warm spicy", "Floral"],
    top: "Cardamom",
    mid: "Leather, Jasmine",
    base: "Amber, Moss, Patchouli",
    price: 139
  },
  {
    id: 146,
    name: "Satin OUD",
    image: "prem7.png",
    images: ["prem7.png", "satinoa1.jpg", "satinoa2.jpg", "infoa.jpg"],
    description: "A concentrated attar version of a luxurious rose-oud composition with creamy vanilla and amber warmth.",
    type: "Attar",
    inspiredBy: "MFK oud Satin Mood",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Floral",
    accords: ["Rose", "Floral", "Oud", "Amber", "Vanilla", "Powdery"],
    top: "Bulgarian Rose, Violet, Strawberry",
    mid: "Turkish Rose",
    base: "Oud (Agarwood), Vanilla, Amber, Benzoin, Caramel, Cedar",
    price: 89
  },
 
// Frontend-only catalogue: product images are intentionally local files in this folder.
...[ 
['Afternoon Dive','LV Afternoon Swim','Unisex','Spring-Summer','Day','Fresh|Citrus|Aquatic','Mandarin Orange, Sicilian Orange, Bergamot.','Ginger.','Ambergris.',499,['afternoon_dive8.png','afternoon_dive20.png','afternoon_dive3.png']],['Al Wadi','Imperial Valley Gissah','Unisex','Autumn-Winter','Night','Woody|Spicy|Amber','Pink Pepper, Bergamot, Davana.','Leather, White Amber, Rosemary.','Oud, Musk, Vetiver.',499,['al_wadi8.png','al_wadi20.png','al_wadi3.png']],['Alpha Blue','YSL Y Le Parfum','Male','Autumn-Winter','Night','Aromatic|Woody|Spicy','Grapefruit, Apple, Ginger.','Lavender, Sage, Geranium.','Tonka Bean, Cedar, Patchouli, Olibanum.',399,['alpha_blue8.png','alpha_blue20.png','alpha_blue3.png']],['Azure Tide','Kaaf Ahmed Al Maghribi','Unisex','Spring-Summer','Day','Fresh|Aquatic|Fruity','Watermelon, Red Fruits, Lavender.','Jasmine, Lotus, Marine Notes.','White Musk, Sandalwood, Ambroxan.',399,['azure_tide8.png','azure_tide20.png','azure_tide3.png']],['Caramel OUD','Caramel OUD','Unisex','Autumn-Winter','Night','Sweet|Oud|Amber','Caramel, Saffron.','Rose, Amber, Praline.','Oud, Vanilla, Musk.',399,['caramel_oud8.png','caramel_oud20.png','caramel_oud3.png']],['Dark Rebel','LV Myriad','Unisex','Autumn-Winter','Night','Oud|Floral|Spicy','Saffron.','Bulgarian Rose, Grasse Rose.','Assam Oud, Cacao, Ambrette, White Musk.',649,['dark_rebel5.png','dark_rebel3.png','dark_rebel1.png']],['Ember','','Unisex','All seasons','Day/Night','Fruity|Musky|Woody','mandarin orange, grapefruit, bergamot, apple, blue orchids','jasmine, lily of the valley, white orchid, pineapple','sandalwood, amber, musk, and vanilla',649,['ember.png']],['Golden Aura','Ajmal Aurum','Unisex','Spring-Summer','Day/Night','Fruity|Floral|Sweet','Lemon, Raspberry, Fruity Notes.','Gardenia, Jasmine, Orange Blossom.','Vanilla, Amber, Musk, Woody Notes.',499,['golden_aura8.png','golden_aura20.png','golden_aura3.png']],['Intus',"Terre D'Hermes",'Male','Spring-Autumn','Day','Woody|Citrus|Spicy','Orange, Grapefruit.','Pepper, Geranium.','Vetiver, Cedar, Patchouli, Benzoin.',399,['intus.png']],['Melior','Xerjoff Naxos','Unisex','Autumn-Winter','Night','Sweet|Tobacco|Aromatic','Lavender, Bergamot, Lemon.','Honey, Cinnamon, Cashmeran, Jasmine Sambac.','Tobacco Leaf, Vanilla, Tonka Bean.',499,['melior.png']],['Million','Paco Rabanne 1 Million','Male','Autumn-Winter','Night','Spicy|Citrus|Leather','Blood Mandarin, Grapefruit, Mint.','Cinnamon, Spicy Notes, Rose.','Amber, Leather, Woody Notes, Patchouli.',399,['million8.png','million20.png','million3.png']],['Mukhallat','','Unisex','Autumn-Winter','Night','Woody|Amber|Spicy','Bergamot, Cardamom, Cinnamon, Fruity Notes.','Lavender, Tobacco, Rose, Spicy Notes.','Amber, Vanilla, Musk, Sandalwood, Oud.',399,['mukhallat8.png','mukhallat20.png','mukhallat3.png']],['Noble','Initio Oud for Greatness','Unisex','Autumn-Winter','Night','Oud|Spicy|Aromatic','Saffron, Nutmeg, Lavender.','Oud.','Patchouli, Musk.',699,['noble.png']],['Ombre','','Unisex','All Seasons','Night','Leather|Smoky|Floral','Cardamom.','Leather, Jasmine Sambac.','Amber, Moss, Patchouli.',449,['ombre.png']],['Pink Vanilla','Kayali Vanilla Candy Rock Sugar','Female','Spring-Autumn','Day/Night','Sweet|Vanilla|Fruity','Candied Pear, Bubble Gum, Vanilla, Violet Leaf.','Caramel, Jasmine, Tonka Bean, Ylang-Ylang, Labdanum.','Rock Sugar, Patchouli, Sandalwood, Cashmere Wood.',399,['pink_vanilla8.png','pink_vanilla20.png','pink_vanilla3.png']],['Qahwa','Lattafa Khamrah Qahwa','Unisex','Autumn-Winter','Night','Spicy|Coffee|Sweet','Cinnamon, Cardamom, Ginger.','Praline, Candied Fruits, White Flowers.','Coffee, Vanilla, Tonka Bean, Benzoin, Musk.',399,['qahwa8.png','qahwa20.png','qahwa3.png']],['Tao Mist','Diptyque Tam Dao','Unisex','Spring-Autumn','Day/Night','Woody|Aromatic|Powdery','Rose, Myrtle, Italian Cypress.','Sandalwood, Cedar.','Spices, Amber, White Musk, Brazilian Rosewood.',399,['tao_mist8.png','tao_mist20.png','tao_mist3.png']],['Urban Icon','Dunhill Icon','Male','Spring-Summer','Day','Fresh|Citrus|Woody','Neroli, Bergamot, Black Pepper, Petitgrain.','Lavender, Cardamom, Juniper Berries, Sage.','Vetiver, Oakmoss, Leather, Oud, Iris.',399,['urban_icon8.png','urban_icon20.png','urban_icon3.png']],['Vanaffe','','Female','Autumn-Winter','Night','Sweet|Coffee|Vanilla','Candied Pear, Bubble Gum, Coffee, Vanilla.','Caramel, Jasmine, Tonka Bean, Coffee Blossom.','Rock Sugar, Vanilla, Sandalwood, Patchouli, Musk.',399,['vanaffe8.png','Vanaffe20.png','vanaffe3.png']],['White OUD','White Oud','Unisex','Autumn-Winter','Night','Oud|Woody|Musky','Bergamot, Saffron, White Pepper.','Rose, Jasmine, White Woods.','White Oud, Musk, Amber, Sandalwood.',399,['white_oud8.png','white_oud20.png','white_oud3.png']],['Symphoria','LV Symphony','Unisex','Spring-Summer','Day','Citrus|Fresh|Fruity','Grapefruit, Bergamot, Orange.','Ginger, Fresh Spices.','Amber, Musk.',699,['symphoria.png']]
].map(([name, inspiredBy, gender, season, time, accords, top, mid, base, price, comboImages], index) => {

  /*
    IMAGE LOGIC
    =========================================================

    Example: "Afternoon Dive"

    DEFAULT THUMBNAIL / 30 ML PREMIUM GIFT:
      afternoon_dive.png

    REGULAR PERFUME BOTTLES:
      8 ml   → afternoon_dive1.png
      20 ml  → afternoon_dive2.png
      30 ml  → afternoon_dive3.png
      50 ml  → afternoon_dive4.png
      100 ml → afternoon_dive5.png

    PREMIUM GIFT PERFUMES:
      30 ml  → afternoon_dive.png
      50 ml  → afternoon_dive7.png
      100 ml → afternoon_dive100.png

    TRANSPARENT COMBO-SET OVERLAYS:
      8 ml   → afternoon_dive8.png
      20 ml  → afternoon_dive20.png
  */

  // Convert product name into filename-safe base:
  // "Afternoon Dive" → "afternoon_dive"
  // "Golden Aura"    → "golden_aura"
  // "White OUD"      → "white_oud"
  const imageBase = name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');

  // Main/default thumbnail.
  // Also represents the 30 ml premium gift perfume.
  const defaultImage = `${imageBase}.png`;

  /*
    Standard product image array.

    IMPORTANT:
    These indexes match your existing PERFUME_VARIANT_INDEX:
      0 = default thumbnail
      1 = 8 ml
      2 = 20 ml
      3 = 30 ml
      4 = 50 ml
      5 = 100 ml
      6 = 30 ml premium gift
      7 = 50 ml premium gift
      8 = 100 ml premium gift
  */
  const variants = [
    defaultImage,                 // [0] Default thumbnail
    `${imageBase}1.png`,          // [1] 8 ml
    `${imageBase}2.png`,          // [2] 20 ml
    `${imageBase}3.png`,          // [3] 30 ml
    `${imageBase}4.png`,          // [4] 50 ml
    `${imageBase}5.png`,          // [5] 100 ml
    defaultImage,                 // [6] 30 ml premium gift = default image
    `${imageBase}7.png`,          // [7] 50 ml premium gift
    `${imageBase}100.png`         // [8] 100 ml premium gift
  ];

  /*
    Transparent PNGs used ONLY for overlapping bottles
    inside the Custom Combo Set box.

    The existing compact array already provides these:
      comboImages[0] = 8 ml transparent PNG
      comboImages[1] = 20 ml transparent PNG

    Example:
      afternoon_dive8.png
      afternoon_dive20.png
  */
  const comboOverlayImages = {
    8: comboImages?.[0] || `${imageBase}8.png`,
    20: comboImages?.[1] || `${imageBase}20.png`
  };

  return {
    id: `frontend_${index + 1}`,
    name,
    type: 'Perfume',
    inspiredBy,
    gender,
    season,
    time,
    family: accords.split('|')[0],
    accords: accords.split('|'),
    top,
    mid,
    base,
    price,

    // Used by product grid thumbnail
    image: defaultImage,

    // Used by regular perfume size and premium gift variants
    images: variants,

    // Used only for transparent overlapping bottles in Custom Set
    comboOverlayImages,

    description: `${accords.replaceAll('|', ', ')} fragrance inspired by ${inspiredBy}.`
  };
})
];

module.exports = products;